# Generated by Django 5.2.4 on 2025-11-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp1', '0003_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='images/defimg.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
